/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workflow names */
        get: operations["listWorkflows"];
        put?: never;
        /** Create a draft workflow */
        post: operations["createWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active workflow spec */
        get: operations["getWorkflow"];
        put?: never;
        post?: never;
        /** Soft-delete a workflow */
        delete: operations["deleteWorkflow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{name}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workflow versions (oldest first) */
        get: operations["listWorkflowVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{name}/versions/{ver}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific workflow version */
        get: operations["getWorkflowVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{name}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote a draft to active */
        post: operations["activateWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{name}/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a workflow synchronously
         * @description Runs the workflow and blocks until completion. For long-running workflows
         *     or LLM token streaming, use `GET /v1/workflows/{name}/stream` instead.
         */
        post: operations["invokeWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{name}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Execute a workflow with SSE streaming
         * @description Runs the workflow and streams execution events as Server-Sent Events.
         *
         *     Event types:
         *     - `step_start` — a graph node began executing
         *     - `llm_token` — one incremental LLM token
         *     - `step_end` — a graph node completed
         *     - `error` — workflow failed; stream closes
         *     - `done` — workflow completed; stream closes
         */
        get: operations["streamWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversation threads */
        get: operations["listThreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get message history for a thread */
        get: operations["getThreadMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active prompt fragments for tenant */
        get: operations["listPrompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force in-process prompt cache refresh */
        post: operations["refreshPrompts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active fragment by slug */
        get: operations["getPrompt"];
        /** Create or update a prompt fragment draft */
        put: operations["upsertPrompt"];
        post?: never;
        /** Soft-delete a prompt fragment */
        delete: operations["deletePrompt"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{slug}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote newest draft to active */
        post: operations["activatePrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{slug}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hard-delete a prompt fragment (irreversible) */
        post: operations["purgePrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{slug}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all versions of a prompt (newest first, metadata only) */
        get: operations["listPromptVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{slug}/versions/{ver}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific prompt version */
        get: operations["getPromptVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (alias) */
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorkflowSpec: {
            /** @example job-search */
            name: string;
            /** @example Multi-agent job search pipeline */
            description?: string;
            steps?: {
                [key: string]: unknown;
            }[];
        };
        WorkflowVersion: {
            /** @example job-search */
            name?: string;
            /** @example sha256:abc123 */
            version?: string;
            /** @enum {string} */
            status?: "draft" | "active";
        };
        WorkflowRequest: {
            /**
             * @description Horizontal-scale coordination key for checkpoint/resume.
             * @example thread-abc123
             */
            thread_id?: string;
            /**
             * @description Workflow-specific input payload.
             * @example {
             *       "query": "senior Go engineer, remote, AI platform"
             *     }
             */
            input: {
                [key: string]: unknown;
            };
        };
        WorkflowResponse: {
            /** @example thread-abc123 */
            thread_id?: string;
            /** @description Workflow output (present on success). */
            output?: {
                [key: string]: unknown;
            };
            /** @description Error message (present on failure). */
            error?: string;
        };
        StreamEvent: {
            /** @enum {string} */
            type: "step_start" | "llm_token" | "step_end" | "error" | "done";
            /** @description Node ID (step_start / step_end). */
            step_id?: string;
            /** @description LLM token fragment (llm_token). */
            token?: string;
            /** @description Final workflow output (done). */
            output?: unknown;
            /** @description Error message (error). */
            error?: string;
        };
        Thread: {
            /** @example thread-abc123 */
            id?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Message: {
            /** @enum {string} */
            role?: "user" | "assistant" | "system" | "tool";
            content?: string;
        };
        Fragment: {
            /** Format: uuid */
            id?: string;
            /** @example system-persona */
            slug?: string;
            content?: string;
            variables?: string[];
            tags?: string[];
            /** @example sha256:abc123 */
            version?: string;
            /** @enum {string} */
            status?: "draft" | "active";
        };
        FragmentBody: {
            content: string;
            variables?: string[];
            tags?: string[];
        };
        /** @description Plain-text error message. */
        ErrorResponse: string;
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Workflow identifier. */
        WorkflowName: string;
        /** @description Prompt fragment slug (URL-safe identifier). */
        PromptSlug: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of workflow names */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example [
                         *       "summarize",
                         *       "job-search",
                         *       "echo"
                         *     ]
                         */
                        workflows?: string[];
                    };
                };
            };
        };
    };
    createWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowSpec"];
            };
        };
        responses: {
            /** @description Draft created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow identifier. */
                name: components["parameters"]["WorkflowName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active workflow spec */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowSpec"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow identifier. */
                name: components["parameters"]["WorkflowName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listWorkflowVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow identifier. */
                name: components["parameters"]["WorkflowName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        versions?: components["schemas"]["WorkflowVersion"][];
                    };
                };
            };
        };
    };
    getWorkflowVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow identifier. */
                name: components["parameters"]["WorkflowName"];
                ver: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow version spec */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowSpec"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    activateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow identifier. */
                name: components["parameters"]["WorkflowName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowVersion"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    invokeWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workflow identifier. */
                name: components["parameters"]["WorkflowName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowRequest"];
            };
        };
        responses: {
            /** @description Workflow completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Workflow execution failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
        };
    };
    streamWorkflow: {
        parameters: {
            query?: {
                /** @description JSON-encoded workflow input. Example `?input={"query":"go engineer"}` */
                input?: string;
            };
            header?: never;
            path: {
                /** @description Workflow identifier. */
                name: components["parameters"]["WorkflowName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listThreads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        threads?: components["schemas"]["Thread"][];
                    };
                };
            };
        };
    };
    getThreadMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        messages?: components["schemas"]["Message"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPrompts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fragment list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        prompts?: components["schemas"]["Fragment"][];
                    };
                };
            };
        };
    };
    refreshPrompts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Prompt fragment slug (URL-safe identifier). */
                slug: components["parameters"]["PromptSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active fragment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fragment"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    upsertPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Prompt fragment slug (URL-safe identifier). */
                slug: components["parameters"]["PromptSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FragmentBody"];
            };
        };
        responses: {
            /** @description Fragment upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fragment"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deletePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Prompt fragment slug (URL-safe identifier). */
                slug: components["parameters"]["PromptSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    activatePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Prompt fragment slug (URL-safe identifier). */
                slug: components["parameters"]["PromptSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activated fragment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fragment"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    purgePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Prompt fragment slug (URL-safe identifier). */
                slug: components["parameters"]["PromptSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purged */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPromptVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Prompt fragment slug (URL-safe identifier). */
                slug: components["parameters"]["PromptSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        versions?: components["schemas"]["Fragment"][];
                    };
                };
            };
        };
    };
    getPromptVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Prompt fragment slug (URL-safe identifier). */
                slug: components["parameters"]["PromptSlug"];
                ver: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fragment at that version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fragment"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
