package llm

import (
	"bytes"
	"fmt"
	"io"
)

// Role identifies the author of a message in a conversation.
type Role string

const (
	// RoleAssistant identifies responses generated by the model.
	RoleAssistant Role = "assistant"
	// RoleSystem provides model-level instructions that precede the conversation.
	RoleSystem Role = "system"
	// RoleTool carries the result of a tool call back to the model.
	RoleTool Role = "tool"
	// RoleUser identifies messages from the human turn.
	RoleUser Role = "user"
)

// ContentPartType identifies the kind of content in a ContentPart.
type ContentPartType string

const (
	// PartTypeText carries plain text.
	PartTypeText ContentPartType = "text"
	// PartTypeImageURL references an image by URL; the provider fetches it.
	PartTypeImageURL ContentPartType = "image_url"
	// PartTypeImageData carries raw image bytes inline (base64-encoded at the wire layer).
	PartTypeImageData ContentPartType = "image_data"
	// PartTypeAudioData carries raw audio bytes inline.
	// Planned support: OpenAI (wav/mp3), Google Gemini (wav/mp3/ogg/flac/aac).
	// No provider adapter currently implements this type.
	PartTypeAudioData ContentPartType = "audio_data"
	// PartTypeVideoData carries raw video bytes inline.
	// Planned support: Google Gemini (mp4/mpeg/mov/avi/webm).
	// No provider adapter currently implements this type.
	PartTypeVideoData ContentPartType = "video_data"
	// PartTypeDocumentData carries raw document bytes inline (PDF, plain text, etc.).
	// Planned support: Anthropic (pdf), Google Gemini (pdf/text).
	// No provider adapter currently implements this type.
	PartTypeDocumentData ContentPartType = "document_data"
	// PartTypeToolCall is emitted by the model to request a tool invocation.
	PartTypeToolCall ContentPartType = "tool_call"
	// PartTypeToolResult carries the output of a tool call back to the model.
	PartTypeToolResult ContentPartType = "tool_result"
)

// ContentPart is one element of a multi-modal message.
//
// Exactly one field group should be populated, determined by Type:
//   - PartTypeText: Text
//   - PartTypeImageURL: ImageURL
//   - PartTypeImageData, PartTypeAudioData, PartTypeVideoData, PartTypeDocumentData: Data + MimeType
//   - PartTypeToolCall: ToolCall
//   - PartTypeToolResult: ToolResult
//
// Use the constructor functions (NewTextPart, NewImageURLPart, NewBinaryPart,
// NewBinaryPartFromBytes) to ensure valid combinations. Call Validate to verify
// an existing ContentPart before passing it to a provider.
//
// Binary part types (image_data, audio_data, video_data, document_data) are
// defined but not yet dispatched by any provider adapter; passing them will
// currently cause an error at the wire layer.
type ContentPart struct {
	Type ContentPartType

	// Text is set when Type == PartTypeText.
	Text string

	// ImageURL is set when Type == PartTypeImageURL.
	ImageURL string

	// Data holds the binary payload for image_data, audio_data, video_data,
	// and document_data parts. Provider adapters read this once when
	// constructing the wire request (base64-encoding as needed).
	// Use NewBinaryPartFromBytes for in-memory slices; NewBinaryPart for streams.
	Data io.Reader

	// DataSize is the byte count of Data. Zero means unknown. Used as a
	// Content-Length hint when uploading to provider file APIs.
	DataSize int64

	// MimeType declares the format of Data (e.g. "image/jpeg", "audio/wav",
	// "video/mp4", "application/pdf"). Required when Data is non-nil.
	MimeType string

	// ToolCall is set when Type == PartTypeToolCall.
	ToolCall *ToolCall

	// ToolResult is set when Type == PartTypeToolResult.
	ToolResult *ToolResult
}

// NewTextPart constructs a text ContentPart.
func NewTextPart(text string) ContentPart {
	return ContentPart{Type: PartTypeText, Text: text}
}

// NewImageURLPart constructs an image-by-URL ContentPart.
func NewImageURLPart(url string) ContentPart {
	return ContentPart{Type: PartTypeImageURL, ImageURL: url}
}

// NewBinaryPart constructs a binary ContentPart from a streaming reader.
// partType must be one of PartTypeImageData, PartTypeAudioData, PartTypeVideoData,
// or PartTypeDocumentData. size is the byte count of data (0 = unknown).
func NewBinaryPart(partType ContentPartType, data io.Reader, size int64, mimeType string) ContentPart {
	return ContentPart{Type: partType, Data: data, DataSize: size, MimeType: mimeType}
}

// NewBinaryPartFromBytes constructs a binary ContentPart from an in-memory slice.
// partType must be one of PartTypeImageData, PartTypeAudioData, PartTypeVideoData,
// or PartTypeDocumentData.
func NewBinaryPartFromBytes(partType ContentPartType, data []byte, mimeType string) ContentPart {
	return ContentPart{
		Type:     partType,
		Data:     bytes.NewReader(data),
		DataSize: int64(len(data)),
		MimeType: mimeType,
	}
}

// Validate returns an error if the ContentPart fields are inconsistent with Type.
func (p ContentPart) Validate() error {
	switch p.Type {
	case PartTypeText:
		if p.Text == "" {
			return fmt.Errorf("llm: text part has empty Text")
		}
	case PartTypeImageURL:
		if p.ImageURL == "" {
			return fmt.Errorf("llm: image_url part has empty ImageURL")
		}
	case PartTypeImageData, PartTypeAudioData, PartTypeVideoData, PartTypeDocumentData:
		if p.Data == nil {
			return fmt.Errorf("llm: %s part has nil Data", p.Type)
		}
		if p.MimeType == "" {
			return fmt.Errorf("llm: %s part has empty MimeType", p.Type)
		}
	case PartTypeToolCall:
		if p.ToolCall == nil {
			return fmt.Errorf("llm: tool_call part has nil ToolCall")
		}
		if p.ToolCall.ID == "" || p.ToolCall.Name == "" {
			return fmt.Errorf("llm: tool_call part requires non-empty ID and Name")
		}
	case PartTypeToolResult:
		if p.ToolResult == nil {
			return fmt.Errorf("llm: tool_result part has nil ToolResult")
		}
		if p.ToolResult.ToolCallID == "" {
			return fmt.Errorf("llm: tool_result part requires non-empty ToolCallID")
		}
	}
	return nil
}

// ToolCall describes a function call the LLM wants to make.
type ToolCall struct {
	ID        string
	Name      string
	Arguments string // JSON-encoded arguments
}

// ToolResult carries the output of a tool call back to the LLM.
type ToolResult struct {
	ToolCallID string
	Content    string
}

// ToolDefinition describes a tool available to the model.
type ToolDefinition struct {
	Name        string
	Description string
	// Parameters is a JSON Schema object describing the tool's input.
	Parameters map[string]any
}

// Request is the canonical input to an LLM call.
type Request struct {
	Messages    []Message
	// Temperature controls response randomness. Not forwarded by all adapters
	// (e.g. the Anthropic adapter ignores Temperature in the current implementation).
	Temperature *float64
	MaxTokens   *int
	// Tools lists the tools available to the model for this call.
	Tools []ToolDefinition
	// Stream indicates the caller wants a streaming response.
	Stream bool
}

// Response is the canonical output from an LLM call.
type Response struct {
	// Content holds the model's text reply (empty if the response is a tool call).
	Content string
	// ToolCalls holds any function calls the model wants to make.
	ToolCalls []ToolCall
	// Usage reports token consumption for cost tracking.
	Usage TokenUsage
	// Model is the model ID that produced this response.
	Model ModelID
}

// TokenUsage tracks token consumption for a single LLM call.
type TokenUsage struct {
	PromptTokens     int
	CompletionTokens int
	TotalTokens      int
	// CachedTokens counts prompt tokens served from the provider's prompt cache.
	CachedTokens int
}

// Chunk is one piece of a streaming response.
type Chunk struct {
	// Delta is the new text fragment in this chunk.
	Delta string
	// ToolCallDelta is a partial tool call update.
	ToolCallDelta *ToolCall
	// Done is true on the final chunk. A non-nil Err implies Done == true.
	Done bool
	// Err is set on the final chunk when the stream ended with an error
	// (e.g. network truncation, scanner error, context cancellation).
	Err error
	// Usage is populated on the final chunk.
	Usage *TokenUsage
}
